version: 2.1
jobs:
  test:
    docker:
      - image: python:3.8  # Replace with your desired Python version

    steps:
      - checkout  # Check out your code repository

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt  # Install your project's dependencies

      - run:
          name: Run unit tests
          command: |
            python -m pytest -v  # Assuming you're using pytest for testing

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
